<div class="contact-us-area pt-100 pb-65">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-lg-12">
                <h4 data-aos="fade-up" data-aos-delay="200">
                    <p><span class="shipping-policy">Our Shipping Policy was last updated on <span
                                    style="background-color:#fff2cc">June 1</span></span>
                    </p>

                    <p><span class="shipping-policy"><b
                                    style="color:black">Interpretation and Definitions</b></span>
                    </p>

                    <p><span class="shipping-policy"><b
                                    style="color:#434343">Interpretation</b></span>
                    </p>

                    <p><span class="shipping-policy">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</span>
                    </p>

                    <p><span class="shipping-policy"><b
                                    style="color:#434343">Definitions</b></span></p>

                    <p><span class="shipping-policy">For the purposes of this Disclaimer:</span>
                    </p>

                    <ul style="list-style: disc!important;margin-left: 40px;">
                        <li><span class="shipping-policy">&quot;Company&quot; (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Disclaimer) refers to <span
                                        style="background-color:#fff2cc">Naiz Trading Private Limited</span></span>
                        </li>
                        <li><span class="shipping-policy">&quot;<strong>Goods</strong>&quot; refers to the items offered for sale on the Service.</span>
                        </li>
                        <li><span class="shipping-policy">&quot;<strong>Orders</strong>&quot; means a request by You to purchase Goods from Us.</span>
                        </li>
                        <li>
                            <span class="shipping-policy">&quot;<strong>Service</strong>&quot; refers to the Website.</span>
                        </li>
                        <li><span class="shipping-policy">&quot;<strong>Website</strong>&quot; refers toNaizaccessible from <span
                                        style="background-color:#fff2cc">https://naizapp.com/index</span></span>
                        </li>
                        <li><span class="shipping-policy">&quot;<strong>You</strong>&quot; means the individual accessing the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</span>
                        </li>
                    </ul>

                    <p></p>
                    <p>
                        <span class="shipping-policy">
                                        <span style="color:black">
                                            Thank you for visiting and shopping at
                                            <span style="background-color:#fff2cc">NaizApp.</span>
                                            The following terms and conditions constitute our Shipping Policy. This Shipping was generated by
                                        </span>
                                <a href="https://www.termsfeed.com">
                                    <span class="shipping-policy">
                                            <span style="color:black;text-decoration: underline">TermsFeed Shipping Policy Generator
                                            </span>
                                    </span>
                                </a>
                                <span class="shipping-policy">
                                        <span style="color:black">.</span>
                                </span>
                        </span>
                    </p>

                    <p><span class="shipping-policy"><b style="color:black">Domestic Shipping Policy</b></span>
                    </p>

                    <p><span class="shipping-policy"><b style="color:#434343">Shipment processing times</b></span>
                    </p>

                    <p><span class="shipping-policy">All Orders are processed within <span
                                    style="background-color:#fff2cc">2-3 business days</span>. Orders are not shipped or delivered on weekends or holidays.</span>
                    </p>

                    <p><span class="shipping-policy">If We are experiencing a high volume of orders, shipments may be delayed by a few days. Please allow additional days in transit for delivery. If there will be a significant delay in shipment of Your Order, We will contact You via email or telephone.</span>
                    </p>

                    <p><span class="shipping-policy">Delivery delays can occasionally occur.</span>
                    </p>

                    <p><span class="shipping-policy"><span style="color:black;background-color:#fff2cc">Naiz app</span>
                            <span class="shipping-policy"> ships to addresses within the U.S., U.S. Territories, and APO/FPO/DPO addresses.</span>
                    </p>

                    <p><span class="shipping-policy"><b
                                    style="color:black">Shipment confirmation &amp; Order tracking</b></span>
                    </p>

                    <p><span class="shipping-policy">You will receive a Shipment Confirmation Email once Your Order has shipped containing your tracking number(s). The tracking number will be active within 24 hours.</span>
                    </p>

                    <p><span class="shipping-policy"><b
                                    style="color:black">Customs, Duties and Taxes</b></span>
                    </p>

                    <p><span class="shipping-policy">
                                    <span style="background-color:#fff2cc">
                                            <span style="color:black">Naiz app</span>
                                    </span>
                            <span style="color:black"> is not responsible for any customs and taxes applied to Your Order. All fees imposed during or after shipping are the responsibility of the customer (tariffs, taxes)</span>
                        </span>
                    </p>

                    <p><span class="shipping-policy"><b style="color:black">Damages</b></span></p>

                    <p>
                        <span class="shipping-policy">
                                    <span style="background-color:#fff2cc">
                                            <span style="color:black">Naiz App</span>
                                    </span>
                            <span style="color:black"> is not liable for any products damaged or lost during shipping. If You received Your Order damaged, please contact the shipment carrier to file a claim.</span>
                        </span>
                    </p>

                    <p><span class="shipping-policy">Please save all packaging materials and damaged goods before filing a claim.</span>
                    </p>

                    <p><span class="shipping-policy"><b style="color:black">Contact Us</b></span></p>

                    <p><span class="shipping-policy">If you have any questions about this Shipping Policy, You can contact Us:</span>
                    </p>

                    <ul style="list-style: disc!important;margin-left: 40px;">
                        <li><span class="shipping-policy">By visiting this page on our website: <span
                                        style="background-color:#fff2cc">https://naizapp.com/index</span></span>
                        </li>
                        <li><span class="shipping-policy">By sending us an email: <span
                                        style="background-color:#fff2cc">naiztrading2021@gmail.com</span></span>
                        </li>
                    </ul>

                </h4>
            </div>
        </div>
    </div>
</div>
